### PR TITLE
undefined method `logger' for Rails:Module

### PR DESCRIPTION
**Pull request by TSMMark**
In some codebases Rails might be defined but not have a logger method defined. This should avoid the issue.

### CODE REVIEW

**Comment by schneems** [comment]
Do you have an example of this happening? I would think not having `Rails.logger` defined would be a bug in an app. Maybe you could show me an https://codetriage.com/example_app showing the problem so I can better understand the fix?

**Comment by schneems** [comment]
Than's for the explanation, this seems good. Can you add a changelog entry for this as it's a change in behavior? 

I think that will also re-trigger CI to run.

**Comment by TSMMark** [comment]
@schneems done

**Comment by schneems** [comment]
Thanks!

**Pull request merged**
